keys:
    - &minotaur age1dp3d8dpfj37g4a2nzg98zx5a9xm2cxh0qrdz4jlz2ed920qqvqysweh9vx
    - &nomad age1dp3d8dpfj37g4a2nzg98zx5a9xm2cxh0qrdz4jlz2ed920qqvqysweh9vx

creation_rules:
    - path_regex: secrets/secrets\.yaml$
      key_groups:
          - age:
                - *minotaur
                - *nomad
