[folders."~/Projects"]
repos = [
    "https://github.com/givikuna/WarframeCardGame.git",
    "https://github.com/rg134/rgtube.git",
    "https://codeberg.org/giviko/struktured.git",
    "https://github.com/givikuna/gitboy.git",
    "https://github.com/givikuna/codensity-transformations-with-yoneda-lemma",
    "https://github.com/givikuna/leetcode-solutions",
    "https://github.com/givikuna/keto-portfolio.git",
    "https://github.com/givikuna/nixboxd.git",
    "https://github.com/givikuna/slay-the-grineer.git",
    "https://github.com/givikuna/raknoid.git",
    "https://github.com/givikuna/TsvariScript.git",
    "https://github.com/givikuna/physics-hw.git",
    "https://github.com/givikuna/ngupp.git",
    "https://github.com/givikuna/gh-api-cli.git",
    "https://github.com/Loid-Project/loid.git",
]

[folders."~/Testing/"]
repos = [
    "https://github.com/givikuna/TEST-auth0_with_expressjs",
    "https://github.com/givikuna/qtuatho0test",
    "https://github.com/givikuna/lean4-playground.git",
]

[folders."~/Documents/Books/"]
repos = [
    "https://github.com/GSimas/Asimov.git"
]
