# colors:

foreground              #d4be98
background              #2c2c2c
selection_foreground    #2c2c2c
selection_background    #e0c28f
url_color               #7daea3

# Black
color0                  #32302f
color8                  #928374

# Red
color1                  #ea6963
color9                  #ea6962

# Orange
color2                  #d8a657
color10                 #d8a657

# Another orange-colored thing
color3                  #ae5328
color11                 #ae5238

# Blue - Teal
color4                  #7daea3
color12                 #7daea3

# Magenta - Pink
color5                  #d3869b
color13                 #d3869b

# Cyan (Aqua)
color6                  #99a8b4
color14                 #99a8b4

# White
color7                  #d4be98
color15                 #dfbf8e


# other stuff:


cursor                  #d4be98
cursor_text_color       #282828

window_padding_width    10

hide_window_decorations yes

font_size               10

font_family             family="RobotoMonoNF-Rg"
bold_font               auto
italic_font             auto
bold_italic_font        auto
