name: CI

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    test:
        name: Evaluate and Run Nixtests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Setup Determine Systems Magic Nix Cache
              uses: DeterminateSystems/magic-nix-cache-action@main

            - name: Verify Flake structure
              run: nix flake check -L

            - name: Run Nixtest Suites
              run: nix run .#tests -- --workers 4
