name: CI

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    test:
        name: Run Nixtests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Setup Magic Nix Cache
              uses: DeterminateSystems/magic-nix-cache-action@main

            - name: Run tests
              run: nix run .#tests
